"""current rev

Revision ID: 2a75906e55d1
Revises: b7c7a263d238
Create Date: 2018-10-14 18:15:27.885482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a75906e55d1'
down_revision = 'b7c7a263d238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('current', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'current')
    # ### end Alembic commands ###
