"""rev position

Revision ID: b7c7a263d238
Revises: bb77cce180bc
Create Date: 2018-10-14 12:45:32.886821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c7a263d238'
down_revision = 'bb77cce180bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('pos', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'pos')
    # ### end Alembic commands ###
